// postgres/postgres_test.go
package postgres_test

import (
	"testing"

	"github.com/danecwalker/ego/postgres"
)

func TestPostgresPlaceholder(t *testing.T) {
	d := postgres.NewDialect()
	if d.Placeholder(1) != "$1" {
		t.Errorf("expected $1, got %s", d.Placeholder(1))
	}
	if d.Placeholder(3) != "$3" {
		t.Errorf("expected $3, got %s", d.Placeholder(3))
	}
}

func TestPostgresQuoteIdentifier(t *testing.T) {
	d := postgres.NewDialect()
	if d.QuoteIdentifier("users") != `"users"` {
		t.Errorf("unexpected quoting")
	}
}

func TestPostgresSupportsReturning(t *testing.T) {
	d := postgres.NewDialect()
	if !d.SupportsReturning() {
		t.Error("postgres should support RETURNING")
	}
}

func TestPostgresTypeMappings(t *testing.T) {
	d := postgres.NewDialect()
	tests := map[string]string{
		"int64":     "BIGINT",
		"int":       "INTEGER",
		"string":    "TEXT",
		"bool":      "BOOLEAN",
		"float64":   "DOUBLE PRECISION",
		"time.Time": "TIMESTAMPTZ",
	}
	for goType, expected := range tests {
		got := d.TypeMapping(goType)
		if got != expected {
			t.Errorf("TypeMapping(%q): expected %q, got %q", goType, expected, got)
		}
	}
}

func TestPostgresAutoIncrementDef(t *testing.T) {
	d := postgres.NewDialect()
	// PostgreSQL uses GENERATED ALWAYS AS IDENTITY or SERIAL, not AUTOINCREMENT
	// For our DDL generation, we return empty string (PG auto-increments with SERIAL type)
	// Or we can return "GENERATED BY DEFAULT AS IDENTITY"
	// Let's keep it simple and use empty string — the TypeMapping for int64 PK will be "BIGSERIAL"
	// Actually the simplest approach: AutoIncrementDef returns "" and we handle PK differently
	// by using BIGSERIAL as the type for PK columns
	// But this doesn't work with the current architecture where TypeMapping is called first, then AutoIncrementDef.
	// Let's return "GENERATED BY DEFAULT AS IDENTITY" which is standard SQL
	result := d.AutoIncrementDef()
	if result == "" {
		t.Error("expected non-empty auto-increment definition for postgres")
	}
}
