// Package postgres provides a PostgreSQL dialect for ego.
//
// To use this package, import the pgx driver in your application:
//
//	import _ "github.com/jackc/pgx/v5/stdlib"
package postgres

import (
	"fmt"
	"strings"

	"github.com/danewilson/ego"
)

type postgresDialect struct{}

func (d *postgresDialect) Name() string { return "postgres" }

func (d *postgresDialect) Placeholder(index int) string {
	return fmt.Sprintf("$%d", index)
}

func (d *postgresDialect) QuoteIdentifier(name string) string {
	return `"` + strings.ReplaceAll(name, `"`, `""`) + `"`
}

func (d *postgresDialect) AutoIncrementDef() string {
	return "GENERATED BY DEFAULT AS IDENTITY"
}

func (d *postgresDialect) SupportsReturning() bool { return true }

func (d *postgresDialect) TypeMapping(goType string) string {
	switch goType {
	case "int64":
		return "BIGINT"
	case "int", "int32":
		return "INTEGER"
	case "int16":
		return "SMALLINT"
	case "string":
		return "TEXT"
	case "bool":
		return "BOOLEAN"
	case "float64":
		return "DOUBLE PRECISION"
	case "float32":
		return "REAL"
	case "time.Time":
		return "TIMESTAMPTZ"
	case "[]byte":
		return "BYTEA"
	default:
		return "TEXT"
	}
}

// NewDialect returns the PostgreSQL dialect implementation.
func NewDialect() ego.Dialect {
	return &postgresDialect{}
}

// New returns a DriverConfig for PostgreSQL with the given connection string.
// Requires github.com/jackc/pgx/v5/stdlib to be imported in the application.
func New(dsn string) ego.DriverConfig {
	return ego.DriverConfig{
		DriverName: "pgx",
		DSN:        dsn,
		Dialect:    &postgresDialect{},
	}
}
